#!/bin/bash
../../../banach --localsenspath ../../ --db-create-tables -QDct t11.time1 -e 1 -B 0.1 -G 10 -xM 3 --one-to-n --increasing-budgets -T 3 combinedschema.sql combinedquery.sql combinedattacker.att
